# Generated by Django 3.2 on 2021-04-12 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210411_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplace',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
