# Generated by Django 3.2 on 2021-04-12 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_marketplace_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='core.cities'),
        ),
    ]
