# Generated by Django 3.2 on 2021-04-16 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='municipiosibge',
            options={'ordering': ['nome']},
        ),
    ]
